# Generated by Django 3.1 on 2020-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecto',
            options={'ordering': ['-creacion'], 'verbose_name': 'Projecto', 'verbose_name_plural': 'Projectos'},
        ),
        migrations.AddField(
            model_name='projecto',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='projectos'),
        ),
    ]
